# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JDXShop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JDXShop
    pod 'Alamofire'
    pod 'DZNEmptyDataSet'
    pod 'QMUIKit'
    pod 'SDCycleScrollView'
    pod 'MJRefresh'
    pod 'SnapKit'
    pod 'HandyJSON', '~> 4.1.1'
    pod 'Kingfisher'
    pod 'Reachability'
    pod 'YYModel'
end
